// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -source=port.go -destination=mocks/port_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "awesome-chat/internal/domain/core/chat/entity"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockRepository) AddMember(ctx context.Context, chatID, memberID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, chatID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRepositoryMockRecorder) AddMember(ctx, chatID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRepository)(nil).AddMember), ctx, chatID, memberID)
}

// AddMembers mocks base method.
func (m *MockRepository) AddMembers(ctx context.Context, chatID uuid.UUID, memberIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, chatID, memberIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockRepositoryMockRecorder) AddMembers(ctx, chatID, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockRepository)(nil).AddMembers), ctx, chatID, memberIDs)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, chatID uuid.UUID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, chatID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, chatID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, chatID, name)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockValidator) Exists(ctx context.Context, chatID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockValidatorMockRecorder) Exists(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockValidator)(nil).Exists), ctx, chatID)
}

// IsMember mocks base method.
func (m *MockValidator) IsMember(ctx context.Context, chatID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockValidatorMockRecorder) IsMember(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockValidator)(nil).IsMember), ctx, chatID, userID)
}

// MockPreviewReader is a mock of PreviewReader interface.
type MockPreviewReader struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewReaderMockRecorder
	isgomock struct{}
}

// MockPreviewReaderMockRecorder is the mock recorder for MockPreviewReader.
type MockPreviewReaderMockRecorder struct {
	mock *MockPreviewReader
}

// NewMockPreviewReader creates a new mock instance.
func NewMockPreviewReader(ctrl *gomock.Controller) *MockPreviewReader {
	mock := &MockPreviewReader{ctrl: ctrl}
	mock.recorder = &MockPreviewReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewReader) EXPECT() *MockPreviewReaderMockRecorder {
	return m.recorder
}

// BatchParticipants mocks base method.
func (m *MockPreviewReader) BatchParticipants(ctx context.Context, chatIDs []uuid.UUID) (map[uuid.UUID][]entity.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchParticipants", ctx, chatIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]entity.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchParticipants indicates an expected call of BatchParticipants.
func (mr *MockPreviewReaderMockRecorder) BatchParticipants(ctx, chatIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchParticipants", reflect.TypeOf((*MockPreviewReader)(nil).BatchParticipants), ctx, chatIDs)
}

// Previews mocks base method.
func (m *MockPreviewReader) Previews(ctx context.Context, userID uuid.UUID) ([]entity.ChatPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Previews", ctx, userID)
	ret0, _ := ret[0].([]entity.ChatPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Previews indicates an expected call of Previews.
func (mr *MockPreviewReaderMockRecorder) Previews(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Previews", reflect.TypeOf((*MockPreviewReader)(nil).Previews), ctx, userID)
}

// MockUserValidator is a mock of UserValidator interface.
type MockUserValidator struct {
	ctrl     *gomock.Controller
	recorder *MockUserValidatorMockRecorder
	isgomock struct{}
}

// MockUserValidatorMockRecorder is the mock recorder for MockUserValidator.
type MockUserValidatorMockRecorder struct {
	mock *MockUserValidator
}

// NewMockUserValidator creates a new mock instance.
func NewMockUserValidator(ctrl *gomock.Controller) *MockUserValidator {
	mock := &MockUserValidator{ctrl: ctrl}
	mock.recorder = &MockUserValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserValidator) EXPECT() *MockUserValidatorMockRecorder {
	return m.recorder
}

// ValidateByID mocks base method.
func (m *MockUserValidator) ValidateByID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateByID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateByID indicates an expected call of ValidateByID.
func (mr *MockUserValidatorMockRecorder) ValidateByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateByID", reflect.TypeOf((*MockUserValidator)(nil).ValidateByID), ctx, userID)
}

// ValidateMultiple mocks base method.
func (m *MockUserValidator) ValidateMultiple(ctx context.Context, userIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateMultiple", ctx, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMultiple indicates an expected call of ValidateMultiple.
func (mr *MockUserValidatorMockRecorder) ValidateMultiple(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMultiple", reflect.TypeOf((*MockUserValidator)(nil).ValidateMultiple), ctx, userIDs)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
