// Code generated by ifacemaker; DO NOT EDIT.

package user

import (
	"awesome-chat/internal/application/user/command"
	"awesome-chat/internal/application/user/query"
	"context"
)

// UseCase ...
type UseCase interface {
	Register(ctx context.Context, in command.RegisterIn) (command.RegisterOut, error)
	Login(ctx context.Context, in command.LoginIn) (command.LoginOut, error)
	Read(ctx context.Context, in query.ReadIn) (query.ReadOut, error)
	List(ctx context.Context, in query.ListIn) (query.ListOut, error)
	ChatIDs(ctx context.Context, in query.ChatIDsIn) (query.ChatIDsOut, error)
}
