// Code generated by gowrap. DO NOT EDIT.
// template: ../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package user

import (
	"awesome-chat/internal/application/user/command"
	"awesome-chat/internal/application/user/query"
	"context"
	"fmt"
)

// UseCaseWithTracing wraps errors from UseCase with operation context.
type UseCaseWithTracing struct {
	_base UseCase
}

// NewUseCaseWithTracing returns a UseCaseWithTracing wrapping the given base implementation.
func NewUseCaseWithTracing(base UseCase) UseCase {
	return &UseCaseWithTracing{_base: base}
}

// ChatIDs implements UseCase.
func (_d *UseCaseWithTracing) ChatIDs(arg0 context.Context, arg1 query.ChatIDsIn) (c2 query.ChatIDsOut, err error) {
	const op = "user.UseCase.ChatIDs"
	c2, err = _d._base.ChatIDs(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// List implements UseCase.
func (_d *UseCaseWithTracing) List(arg0 context.Context, arg1 query.ListIn) (l1 query.ListOut, err error) {
	const op = "user.UseCase.List"
	l1, err = _d._base.List(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Login implements UseCase.
func (_d *UseCaseWithTracing) Login(arg0 context.Context, arg1 command.LoginIn) (l1 command.LoginOut, err error) {
	const op = "user.UseCase.Login"
	l1, err = _d._base.Login(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Read implements UseCase.
func (_d *UseCaseWithTracing) Read(arg0 context.Context, arg1 query.ReadIn) (r1 query.ReadOut, err error) {
	const op = "user.UseCase.Read"
	r1, err = _d._base.Read(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Register implements UseCase.
func (_d *UseCaseWithTracing) Register(arg0 context.Context, arg1 command.RegisterIn) (r1 command.RegisterOut, err error) {
	const op = "user.UseCase.Register"
	r1, err = _d._base.Register(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
