// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/handler_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	command "awesome-chat/internal/application/chat/command"
	query "awesome-chat/internal/application/chat/query"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockuseCase) AddMember(ctx context.Context, in command.AddMemberIn) (command.AddMemberOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, in)
	ret0, _ := ret[0].(command.AddMemberOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockuseCaseMockRecorder) AddMember(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockuseCase)(nil).AddMember), ctx, in)
}

// Create mocks base method.
func (m *MockuseCase) Create(ctx context.Context, in command.CreateIn) (command.CreateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(command.CreateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuseCaseMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuseCase)(nil).Create), ctx, in)
}

// Previews mocks base method.
func (m *MockuseCase) Previews(ctx context.Context, in query.PreviewsIn) (query.PreviewsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Previews", ctx, in)
	ret0, _ := ret[0].(query.PreviewsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Previews indicates an expected call of Previews.
func (mr *MockuseCaseMockRecorder) Previews(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Previews", reflect.TypeOf((*MockuseCase)(nil).Previews), ctx, in)
}
