// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/handler_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	command "awesome-chat/internal/application/message/command"
	query "awesome-chat/internal/application/message/query"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// CreateVoiceUpload mocks base method.
func (m *MockuseCase) CreateVoiceUpload(ctx context.Context, in command.CreateVoiceUploadIn) (command.CreateVoiceUploadOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVoiceUpload", ctx, in)
	ret0, _ := ret[0].(command.CreateVoiceUploadOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVoiceUpload indicates an expected call of CreateVoiceUpload.
func (mr *MockuseCaseMockRecorder) CreateVoiceUpload(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVoiceUpload", reflect.TypeOf((*MockuseCase)(nil).CreateVoiceUpload), ctx, in)
}

// List mocks base method.
func (m *MockuseCase) List(ctx context.Context, in query.ListIn) (query.ListOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, in)
	ret0, _ := ret[0].(query.ListOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuseCaseMockRecorder) List(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuseCase)(nil).List), ctx, in)
}

// Send mocks base method.
func (m *MockuseCase) Send(ctx context.Context, in command.SendIn) (command.SendOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, in)
	ret0, _ := ret[0].(command.SendOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockuseCaseMockRecorder) Send(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockuseCase)(nil).Send), ctx, in)
}

// SendVoice mocks base method.
func (m *MockuseCase) SendVoice(ctx context.Context, in command.SendVoiceIn) (command.SendVoiceOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVoice", ctx, in)
	ret0, _ := ret[0].(command.SendVoiceOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendVoice indicates an expected call of SendVoice.
func (mr *MockuseCaseMockRecorder) SendVoice(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVoice", reflect.TypeOf((*MockuseCase)(nil).SendVoice), ctx, in)
}
