// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package message

import (
	"context"
	"fmt"

	awesomechatv1 "github.com/D1sordxr/awesome-chat-proto/gen/go/awesomechat/v1"
)

// HandlerWithTracing wraps errors from Handler with operation context.
type HandlerWithTracing struct {
	_base Handler
}

// NewHandlerWithTracing returns a HandlerWithTracing wrapping the given base implementation.
func NewHandlerWithTracing(base Handler) Handler {
	return &HandlerWithTracing{_base: base}
}

// CreateVoiceUpload implements Handler.
func (_d *HandlerWithTracing) CreateVoiceUpload(arg0 context.Context, arg1 *awesomechatv1.CreateVoiceUploadRequest) (cp2 *awesomechatv1.CreateVoiceUploadResponse, err error) {
	const op = "message.Handler.CreateVoiceUpload"
	cp2, err = _d._base.CreateVoiceUpload(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// ListMessages implements Handler.
func (_d *HandlerWithTracing) ListMessages(arg0 context.Context, arg1 *awesomechatv1.ListMessagesRequest) (lp2 *awesomechatv1.ListMessagesResponse, err error) {
	const op = "message.Handler.ListMessages"
	lp2, err = _d._base.ListMessages(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// SendMessage implements Handler.
func (_d *HandlerWithTracing) SendMessage(arg0 context.Context, arg1 *awesomechatv1.SendMessageRequest) (sp2 *awesomechatv1.SendMessageResponse, err error) {
	const op = "message.Handler.SendMessage"
	sp2, err = _d._base.SendMessage(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// SendVoiceMessage implements Handler.
func (_d *HandlerWithTracing) SendVoiceMessage(arg0 context.Context, arg1 *awesomechatv1.SendVoiceMessageRequest) (sp2 *awesomechatv1.SendVoiceMessageResponse, err error) {
	const op = "message.Handler.SendVoiceMessage"
	sp2, err = _d._base.SendVoiceMessage(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
