// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/interceptors_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	vo "awesome-chat/internal/domain/core/user/vo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktokenParser is a mock of tokenParser interface.
type MocktokenParser struct {
	ctrl     *gomock.Controller
	recorder *MocktokenParserMockRecorder
	isgomock struct{}
}

// MocktokenParserMockRecorder is the mock recorder for MocktokenParser.
type MocktokenParserMockRecorder struct {
	mock *MocktokenParser
}

// NewMocktokenParser creates a new mock instance.
func NewMocktokenParser(ctrl *gomock.Controller) *MocktokenParser {
	mock := &MocktokenParser{ctrl: ctrl}
	mock.recorder = &MocktokenParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenParser) EXPECT() *MocktokenParserMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MocktokenParser) Do(token vo.JWTToken) (vo.IDClaims, vo.EmailClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", token)
	ret0, _ := ret[0].(vo.IDClaims)
	ret1, _ := ret[1].(vo.EmailClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Do indicates an expected call of Do.
func (mr *MocktokenParserMockRecorder) Do(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MocktokenParser)(nil).Do), token)
}
