storage:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  port: 5432
  database: "awesome-chat-db"

stream_subscriber:
  client_address: "localhost:6379"
  password: "awesome-password"
