// Code generated by ifacemaker; DO NOT EDIT.

package chat

import (
	"awesome-chat/internal/application/chat/command"
	"awesome-chat/internal/application/chat/query"
	"context"
)

// UseCase ...
type UseCase interface {
	Create(ctx context.Context, in command.CreateIn) (command.CreateOut, error)
	AddMember(ctx context.Context, in command.AddMemberIn) (command.AddMemberOut, error)
	Previews(ctx context.Context, in query.PreviewsIn) (query.PreviewsOut, error)
}
