// Code generated by gowrap. DO NOT EDIT.
// template: ../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package chat

import (
	"awesome-chat/internal/application/chat/command"
	"awesome-chat/internal/application/chat/query"
	"context"
	"fmt"
)

// UseCaseWithTracing wraps errors from UseCase with operation context.
type UseCaseWithTracing struct {
	_base UseCase
}

// NewUseCaseWithTracing returns a UseCaseWithTracing wrapping the given base implementation.
func NewUseCaseWithTracing(base UseCase) UseCase {
	return &UseCaseWithTracing{_base: base}
}

// AddMember implements UseCase.
func (_d *UseCaseWithTracing) AddMember(arg0 context.Context, arg1 command.AddMemberIn) (a1 command.AddMemberOut, err error) {
	const op = "chat.UseCase.AddMember"
	a1, err = _d._base.AddMember(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Create implements UseCase.
func (_d *UseCaseWithTracing) Create(arg0 context.Context, arg1 command.CreateIn) (c2 command.CreateOut, err error) {
	const op = "chat.UseCase.Create"
	c2, err = _d._base.Create(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Previews implements UseCase.
func (_d *UseCaseWithTracing) Previews(arg0 context.Context, arg1 query.PreviewsIn) (p1 query.PreviewsOut, err error) {
	const op = "chat.UseCase.Previews"
	p1, err = _d._base.Previews(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
