// Code generated by gowrap. DO NOT EDIT.
// template: ../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package message

import (
	"awesome-chat/internal/application/message/command"
	"awesome-chat/internal/application/message/query"
	"context"
	"fmt"
)

// UseCaseWithTracing wraps errors from UseCase with operation context.
type UseCaseWithTracing struct {
	_base UseCase
}

// NewUseCaseWithTracing returns a UseCaseWithTracing wrapping the given base implementation.
func NewUseCaseWithTracing(base UseCase) UseCase {
	return &UseCaseWithTracing{_base: base}
}

// CreateVoiceUpload implements UseCase.
func (_d *UseCaseWithTracing) CreateVoiceUpload(arg0 context.Context, arg1 command.CreateVoiceUploadIn) (c2 command.CreateVoiceUploadOut, err error) {
	const op = "message.UseCase.CreateVoiceUpload"
	c2, err = _d._base.CreateVoiceUpload(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// List implements UseCase.
func (_d *UseCaseWithTracing) List(arg0 context.Context, arg1 query.ListIn) (l1 query.ListOut, err error) {
	const op = "message.UseCase.List"
	l1, err = _d._base.List(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Send implements UseCase.
func (_d *UseCaseWithTracing) Send(arg0 context.Context, arg1 command.SendIn) (s1 command.SendOut, err error) {
	const op = "message.UseCase.Send"
	s1, err = _d._base.Send(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// SendVoice implements UseCase.
func (_d *UseCaseWithTracing) SendVoice(arg0 context.Context, arg1 command.SendVoiceIn) (s1 command.SendVoiceOut, err error) {
	const op = "message.UseCase.SendVoice"
	s1, err = _d._base.SendVoice(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
