// Code generated by ifacemaker; DO NOT EDIT.

package message

import (
	"awesome-chat/internal/application/message/command"
	"awesome-chat/internal/application/message/query"
	"context"
)

// UseCase ...
type UseCase interface {
	Send(ctx context.Context, in command.SendIn) (command.SendOut, error)
	CreateVoiceUpload(ctx context.Context, in command.CreateVoiceUploadIn) (command.CreateVoiceUploadOut, error)
	SendVoice(ctx context.Context, in command.SendVoiceIn) (command.SendVoiceOut, error)
	List(ctx context.Context, in query.ListIn) (query.ListOut, error)
}
