// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -source=port.go -destination=mocks/port_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "awesome-chat/internal/domain/core/message/entity"
	vo "awesome-chat/internal/domain/core/message/vo"
	entity0 "awesome-chat/internal/domain/core/shared/outbox/entity"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, message entity.Message) (entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, message)
	ret0, _ := ret[0].(entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, message)
}

// MockVoiceRepository is a mock of VoiceRepository interface.
type MockVoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVoiceRepositoryMockRecorder
	isgomock struct{}
}

// MockVoiceRepositoryMockRecorder is the mock recorder for MockVoiceRepository.
type MockVoiceRepositoryMockRecorder struct {
	mock *MockVoiceRepository
}

// NewMockVoiceRepository creates a new mock instance.
func NewMockVoiceRepository(ctrl *gomock.Controller) *MockVoiceRepository {
	mock := &MockVoiceRepository{ctrl: ctrl}
	mock.recorder = &MockVoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoiceRepository) EXPECT() *MockVoiceRepositoryMockRecorder {
	return m.recorder
}

// SaveVoice mocks base method.
func (m *MockVoiceRepository) SaveVoice(ctx context.Context, data vo.SaveVoiceData) (entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVoice", ctx, data)
	ret0, _ := ret[0].(entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveVoice indicates an expected call of SaveVoice.
func (mr *MockVoiceRepositoryMockRecorder) SaveVoice(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVoice", reflect.TypeOf((*MockVoiceRepository)(nil).SaveVoice), ctx, data)
}

// MockOutbox is a mock of Outbox interface.
type MockOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMockRecorder
	isgomock struct{}
}

// MockOutboxMockRecorder is the mock recorder for MockOutbox.
type MockOutboxMockRecorder struct {
	mock *MockOutbox
}

// NewMockOutbox creates a new mock instance.
func NewMockOutbox(ctrl *gomock.Controller) *MockOutbox {
	mock := &MockOutbox{ctrl: ctrl}
	mock.recorder = &MockOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutbox) EXPECT() *MockOutboxMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockOutbox) Save(ctx context.Context, outbox entity0.Outbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, outbox)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOutboxMockRecorder) Save(ctx, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOutbox)(nil).Save), ctx, outbox)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockReader) List(ctx context.Context, filter vo.ReadFilter) ([]entity.MessageForPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.MessageForPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReaderMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReader)(nil).List), ctx, filter)
}

// MockUploadService is a mock of UploadService interface.
type MockUploadService struct {
	ctrl     *gomock.Controller
	recorder *MockUploadServiceMockRecorder
	isgomock struct{}
}

// MockUploadServiceMockRecorder is the mock recorder for MockUploadService.
type MockUploadServiceMockRecorder struct {
	mock *MockUploadService
}

// NewMockUploadService creates a new mock instance.
func NewMockUploadService(ctrl *gomock.Controller) *MockUploadService {
	mock := &MockUploadService{ctrl: ctrl}
	mock.recorder = &MockUploadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadService) EXPECT() *MockUploadServiceMockRecorder {
	return m.recorder
}

// PresignedPut mocks base method.
func (m *MockUploadService) PresignedPut(ctx context.Context, objectKey string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedPut", ctx, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PresignedPut indicates an expected call of PresignedPut.
func (mr *MockUploadServiceMockRecorder) PresignedPut(ctx, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedPut", reflect.TypeOf((*MockUploadService)(nil).PresignedPut), ctx, objectKey)
}

// MockChatValidator is a mock of ChatValidator interface.
type MockChatValidator struct {
	ctrl     *gomock.Controller
	recorder *MockChatValidatorMockRecorder
	isgomock struct{}
}

// MockChatValidatorMockRecorder is the mock recorder for MockChatValidator.
type MockChatValidatorMockRecorder struct {
	mock *MockChatValidator
}

// NewMockChatValidator creates a new mock instance.
func NewMockChatValidator(ctrl *gomock.Controller) *MockChatValidator {
	mock := &MockChatValidator{ctrl: ctrl}
	mock.recorder = &MockChatValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatValidator) EXPECT() *MockChatValidatorMockRecorder {
	return m.recorder
}

// IsMember mocks base method.
func (m *MockChatValidator) IsMember(ctx context.Context, chatID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockChatValidatorMockRecorder) IsMember(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockChatValidator)(nil).IsMember), ctx, chatID, userID)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
