// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package user

import (
	"context"
	"fmt"

	awesomechatv1 "github.com/D1sordxr/awesome-chat-proto/gen/go/awesomechat/v1"
)

// HandlerWithTracing wraps errors from Handler with operation context.
type HandlerWithTracing struct {
	_base Handler
}

// NewHandlerWithTracing returns a HandlerWithTracing wrapping the given base implementation.
func NewHandlerWithTracing(base Handler) Handler {
	return &HandlerWithTracing{_base: base}
}

// GetCurrentUser implements Handler.
func (_d *HandlerWithTracing) GetCurrentUser(arg0 context.Context, arg1 *awesomechatv1.GetCurrentUserRequest) (gp2 *awesomechatv1.GetCurrentUserResponse, err error) {
	const op = "user.Handler.GetCurrentUser"
	gp2, err = _d._base.GetCurrentUser(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// ListUserChatIds implements Handler.
func (_d *HandlerWithTracing) ListUserChatIds(arg0 context.Context, arg1 *awesomechatv1.ListUserChatIdsRequest) (lp2 *awesomechatv1.ListUserChatIdsResponse, err error) {
	const op = "user.Handler.ListUserChatIds"
	lp2, err = _d._base.ListUserChatIds(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// ListUsers implements Handler.
func (_d *HandlerWithTracing) ListUsers(arg0 context.Context, arg1 *awesomechatv1.ListUsersRequest) (lp2 *awesomechatv1.ListUsersResponse, err error) {
	const op = "user.Handler.ListUsers"
	lp2, err = _d._base.ListUsers(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Login implements Handler.
func (_d *HandlerWithTracing) Login(arg0 context.Context, arg1 *awesomechatv1.LoginRequest) (lp2 *awesomechatv1.LoginResponse, err error) {
	const op = "user.Handler.Login"
	lp2, err = _d._base.Login(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Logout implements Handler.
func (_d *HandlerWithTracing) Logout(arg0 context.Context, arg1 *awesomechatv1.LogoutRequest) (lp2 *awesomechatv1.LogoutResponse, err error) {
	const op = "user.Handler.Logout"
	lp2, err = _d._base.Logout(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// Register implements Handler.
func (_d *HandlerWithTracing) Register(arg0 context.Context, arg1 *awesomechatv1.RegisterRequest) (rp2 *awesomechatv1.RegisterResponse, err error) {
	const op = "user.Handler.Register"
	rp2, err = _d._base.Register(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
