// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/handler_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	command "awesome-chat/internal/application/user/command"
	query "awesome-chat/internal/application/user/query"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
	isgomock struct{}
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// ChatIDs mocks base method.
func (m *MockuseCase) ChatIDs(ctx context.Context, in query.ChatIDsIn) (query.ChatIDsOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatIDs", ctx, in)
	ret0, _ := ret[0].(query.ChatIDsOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatIDs indicates an expected call of ChatIDs.
func (mr *MockuseCaseMockRecorder) ChatIDs(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatIDs", reflect.TypeOf((*MockuseCase)(nil).ChatIDs), ctx, in)
}

// List mocks base method.
func (m *MockuseCase) List(ctx context.Context, in query.ListIn) (query.ListOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, in)
	ret0, _ := ret[0].(query.ListOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuseCaseMockRecorder) List(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuseCase)(nil).List), ctx, in)
}

// Login mocks base method.
func (m *MockuseCase) Login(ctx context.Context, in command.LoginIn) (command.LoginOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, in)
	ret0, _ := ret[0].(command.LoginOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockuseCaseMockRecorder) Login(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockuseCase)(nil).Login), ctx, in)
}

// Read mocks base method.
func (m *MockuseCase) Read(ctx context.Context, in query.ReadIn) (query.ReadOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, in)
	ret0, _ := ret[0].(query.ReadOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockuseCaseMockRecorder) Read(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockuseCase)(nil).Read), ctx, in)
}

// Register mocks base method.
func (m *MockuseCase) Register(ctx context.Context, in command.RegisterIn) (command.RegisterOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, in)
	ret0, _ := ret[0].(command.RegisterOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockuseCaseMockRecorder) Register(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockuseCase)(nil).Register), ctx, in)
}
