// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../pkg/gowrap/tracing.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package chat

import (
	"context"
	"fmt"

	awesomechatv1 "github.com/D1sordxr/awesome-chat-proto/gen/go/awesomechat/v1"
)

// HandlerWithTracing wraps errors from Handler with operation context.
type HandlerWithTracing struct {
	_base Handler
}

// NewHandlerWithTracing returns a HandlerWithTracing wrapping the given base implementation.
func NewHandlerWithTracing(base Handler) Handler {
	return &HandlerWithTracing{_base: base}
}

// AddMember implements Handler.
func (_d *HandlerWithTracing) AddMember(arg0 context.Context, arg1 *awesomechatv1.AddMemberRequest) (ap2 *awesomechatv1.AddMemberResponse, err error) {
	const op = "chat.Handler.AddMember"
	ap2, err = _d._base.AddMember(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// CreateChat implements Handler.
func (_d *HandlerWithTracing) CreateChat(arg0 context.Context, arg1 *awesomechatv1.CreateChatRequest) (cp2 *awesomechatv1.CreateChatResponse, err error) {
	const op = "chat.Handler.CreateChat"
	cp2, err = _d._base.CreateChat(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// ListChatPreviews implements Handler.
func (_d *HandlerWithTracing) ListChatPreviews(arg0 context.Context, arg1 *awesomechatv1.ListChatPreviewsRequest) (lp2 *awesomechatv1.ListChatPreviewsResponse, err error) {
	const op = "chat.Handler.ListChatPreviews"
	lp2, err = _d._base.ListChatPreviews(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
