storage:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  port: 5432
  database: "awesome-chat-db"
  migration: true

http:
  address: "localhost"
  port: "8081"
  timeout: 4s
  idle_timeout: 30s

broker:
  brokers:
    - "kafka:9092"
  topic: "awesome-chat-message"
